### ISSUE TITLE
sixel image with specific height and terminal font height cause broken image display

### ISSUE THREAD

**Issue by blcc** [bakkeby/st-flexipatch#108]
Hi,
For example, terminal font height 18px then the line height will be set as 22px.
When display a figure with 482px height image, the image height will be set as 484px (22 lines).
Which is at line 481 of sixel.c
But when sixel codec be process to last line, it will be treat as wrong image size at line 349.
Then the image will be resize to a mess.

My solution is insert this in line 482 of sixel.c:
`sy = sy + (6-sy%6)%6;`  //but follow one line be covered.
or
`if (sy%6 > 0) sy = sy+st->grid_height;` //but too many space below image
or simply remove the '+ 6' after st->pos_y in line 349.

Any idea?

**Comment by veltza** [comment]
I can reproduce this. Interestingly, this doesn't happen on my st fork, so I'll have a look and come back tomorrow.

**Comment by veltza** [comment]
Here is my analysis of this issue.

When the parsed sixel image is larger than the image buffer, the width and height of the buffer are [doubled](https://github.com/bakkeby/st-flexipatch/blob/3fcf0e3db74b906c4802eeb2fd0b93c89e0de4a7/sixel.c#L349). That is fine, because the buffer size is [resized](https://github.com/bakkeby/st-flexipatch/blob/3fcf0e3db74b906c4802eeb2fd0b93c89e0de4a7/sixel.c#L236) back to the final image size when `sixel_parser_finalize()` is called. But the problem is that the width and height of the image are [read](https://github.com/bakkeby/st-flexipatch/blob/3fcf0e3db74b906c4802eeb2fd0b93c89e0de4a7/st.c#L2655) from the sixel engine before the function is called, so the pixel buffer is larger than the final image:

```c
	new_image->width = sixel_st.image.width;
	new_image->height = sixel_st.image.height;
	new_image->pixels = malloc(new_image->width * new_image->height * 4);
	if (sixel_parser_finalize(&sixel_st, new_image->pixels) != 0) {
		perror("sixel_parser_finalize() failed");
		sixel_parser_deinit(&sixel_st);
		return;
	}
```

So when the image buffer is resized back to the final image size in `sixel_parser_finalize()`, the [conversion loop](https://github.com/bakkeby/st-flexipatch/blob/3fcf0e3db74b906c4802eeb2fd0b93c89e0de4a7/sixel.c#L249) thinks that the image buffer and the pixel buffer are the same size and messes up the image:

```c
	for (y = 0; y < st->image.height; ++y) {
		for (x = 0; x < st->image.width; ++x) {
			color = st->image.palette[*src++];
			*dst++ = color >> 16 & 0xff;   /* b */
			*dst++ = color >> 8 & 0xff;    /* g */
			*dst++ = color >> 0 & 0xff;    /* r */
			*dst++ = color >> 24 & 0xff;   /* a */
		}
		/* fill right padding with bgcolor */
		for (; x < st->image.width; ++x) {
			color = st->image.palette[0];  /* bgcolor */
			*dst++ = color >> 16 & 0xff;   /* b */
			*dst++ = color >> 8 & 0xff;    /* g */
			*dst++ = color >> 0 & 0xff;    /* r */
			*dst++ = color >> 24 & 0xff;   /* a */
		}
	}
```

So you get something like this:
![a1](https://github.com/bakkeby/st-flexipatch/assets/106755522/6b61b560-89da-42c3-b8c7-53e3603ea5b0)

Instead of this:
![a2](https://github.com/bakkeby/st-flexipatch/assets/106755522/e50dcff7-5609-4edb-bf4c-34530fcea6b4)

Interestingly, my [unmerged PR](https://github.com/bakkeby/st-flexipatch/pull/103) accidentally fixes this issue as well when it removes the black bars from the sixel images. So I need to create a new PR based on the unmerged PR to fix this issue. But I also need to fix edge cases that cause unnecessary image buffer resizing when image buffer height is not divisible by 6 (sixel height).

**Comment by veltza** [comment]
I also found a bug that could cause a segmentation fault if the height of the image is greater than DECSIXEL_HEIGHT_MAX:

```c
if (st->repeat_count > 0 && st->pos_y - 5 < image->height) {
```

It should be `+ 5` not `- 5`. I'll fix that too.

**Comment by veltza** [comment]
@blcc I created a new [PR](https://github.com/bakkeby/st-flexipatch/pull/109) to fix this issue. Would you like to test it before the merge?

**Comment by blcc** [comment]
Tested. Work perfect!
Thank you very much.
