### ISSUE TITLE
Support for OSC 7

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/st-flexipatch#153]
`foot` terminal [uses OSC 7](https://codeberg.org/dnkl/foot/wiki#spawning-new-terminal-instances-in-the-current-working-directory) to figure out the current working directory. I know we already support keybindings for launching a new terminal in the current working directory. But I feel this would be a more general solution and I can just rely on my zshrc function across multiple terminals.

If this seems worthwhile for the project, please let me know how I could get started and I would love to take a crack at this.

**Comment by veltza** [comment]
I've already implemented this in st-sx, so if you want to create a patch from that implementation, you can start from this [commit](https://github.com/veltza/st-sx/commit/817865c2c6ed905af8849580e58bdcf399216fbd).

Alternatively, you could also fix the current newterm patch so that it would take the current working directory from the foreground process. 

The algorithm should work like this:

1. Get the foreground process group id: `pid_t pgid = tcgetpgrp(cmdfd);`

2. Go through the processes that have the same `pgid` and choose the one you think is the foreground process. Kitty chooses the process with [the highest PID,](https://github.com/kovidgoyal/kitty/blob/08931a9aba93f853427c13c76645edde41729e87/kitty/child.py#L444-L457) which seems reasonable.

3. Get the CWD from the process

That would make the newterm much more usable because it could take the CWD from any foreground process like a terminal file manager.

**Comment by UtkarshVerma** [comment]
I have created a PR from your commit for now. It doesn't include the foreground process CWD fetching though as OSC7 seems pretty solid by itself.

Thanks!

**Comment by veltza** [comment]
> Alternatively, you could also fix the current newterm patch so that it would take the current working directory from the foreground process.

I wrote a function that does this. It should work exactly like Kitty with [new_os_window_with_cwd](https://sw.kovidgoyal.net/kitty/actions/#action-new_os_window).

The problem with OSC 7 is that every application has to support it and that will never happen because not all terminal emulators support it either. For example, the Yazi file manager doesn't support it, so I can't open a new terminal window to the directory where Yazi is. But with the function below I can.

I'll leave it here in case anyone finds it useful.

```c
#include <dirent.h>

/* Get the current working directory of the foreground process */
static char *
get_foreground_cwd(void)
{
	static char cwd[32];
	struct dirent *entry;
	char junk;
	DIR *dir;
	pid_t epid, fgpid = 0, pgid = tcgetpgrp(cmdfd);

	/* Find the foreground process in the foreground process group. We assume
	 * that the process with the highest PID is the active foreground process.
	 * The Kitty terminal also uses a similar solution:
	 * https://github.com/kovidgoyal/kitty/blob/70d72b22d89e926e41ba587e4976db53dad21248/kitty/child.py#L444-L457
	 */
	if (pgid > 0 && (dir = opendir("/proc"))) {
		while ((entry = readdir(dir))) {
			if (sscanf(entry->d_name, "%d%c", &epid, &junk) == 1)
				fgpid = (epid > fgpid && getpgid(epid) == pgid) ? epid : fgpid;
		}
		closedir(dir);
	}

	/* Note that if we didn't get the fg process, we fall back to the shell's PID */
	snprintf(cwd, sizeof cwd, "/proc/%ld/cwd", (fgpid > 0) ? (long)fgpid : (long)pid);
	return cwd;
}
```

**Comment by bakkeby** [comment]
In my experience the `/proc/<pid>/cwd` is often not updated for graphical applications, likely because they have a different way of handling the currently open file / document.

For that reason the [spawn cwd](https://dwm.suckless.org/patches/spawn_cwd/) patch for dwm uses a really hacky solution which is to derive the path based on the window title. Not suggesting to do that here of course.

**Comment by veltza** [comment]
I'm talking about terminal applications because [tcgetpgrp](https://www.man7.org/linux/man-pages/man3/tcsetpgrp.3.html) returns the foreground process group that is currently running on the terminal emulator.

**Comment by bakkeby** [comment]
Yes it may very well be the case that `/proc/<pid>/cwd` is maintained more often for terminal applications.

It makes sense to look up the cwd from the currently running process at least when alt screen is active, as you say it doesn't make much sense to use the shell's cwd as it may not be right in the given context. I don't see a problem incorporating the `get_foreground_cwd` function into this feature.

**Comment by veltza** [comment]
It is true that if an application does not actually change the working directory, then `get_foreground_cwd` does not work. But then again, if an application doesn't emit the OSC 7 sequence, it won't work either. So far, I've only seen one application that won't let you change the current working directory, and that is the nano editor.

However, there is at least one drawback compared to the current implementation. If a script is running, a new terminal window will open in the script's working directory. And it might be a different directory than where you started the script.

For this reason, the newterm could have two modes:
* newterm {.i =  0} would use the current implementation
* newterm {.i =  1} would use the `get_foreground_cwd`

This way it would be backwards compatible and you could even have shortcuts for both.
