### ISSUE TITLE
Unable to use externalpipe with right-click-to-plumb and/or opencopied patches

### ISSUE THREAD

**Issue by Barbarossa93** [bakkeby/st-flexipatch#27]
As the title says, the patches don't seem to work together. If they're all enabled (or external pipe and one of the others is enabled) using the opencopied command or making a right click on a selection freezes the st window. I assume that this is probably intentional, but I thought I'd ask because I'm not sure.

I would really like to have the ability of having both the external pipe and right-click-to-plumb. If indeed these two patches aren't meant to work out of the box together, is there a way to make them cooperate? It looks like there's a newer version of right-click-to-plumb if that helps https://st.suckless.org/patches/right_click_to_plumb/

**Comment by bakkeby** [comment]
I find that the reason for this is because of the changes the externalpipe. The thing is I don't quite understand why they are needed - both externalpipe and right click to plumb seem to work just fine without them.

**Comment by bakkeby** [comment]
`sigchld` seems to be called only after the first command you run, be that the externalpipe command or the right click to plumb command.

**Comment by bakkeby** [comment]
Ideally I'd just delete the externalpipe changes to `sigchld` as it seems to work without it, but since I don't know the actual underlying reasoning for the changes in the first place I went with another solution to only use those changes if the command run was the externalpipe command, otherwise leaving the `sigchld` to behave as normal for other patches such as right-click-to-plumb or opencopied. Have a look to see if this fixes the issue for you.

**Comment by Barbarossa93** [comment]
Looks like it works! Thanks @bakkeby!!
