### ISSUE TITLE
Replace current incomplete sixel patch

### ISSUE THREAD

**Issue by AlexKurisu** [bakkeby/st-flexipatch#30]
Please consider replacing current incomplete (and partially broken) implementation of sixel with a self-made patch based on works of https://github.com/galatolofederico/st-sixel. Mentioned project has a lot more complete implementation of sixel. Or you can use mentioned project as a source of bugfixes for sixel.

**Comment by bakkeby** [comment]
How does that project have a more complete implementation of sixel? It has the same sixel.c and sixel_hls.c files.

The only thing that I can see is that Charles Daniels hacked around a lot to avoid images disappearing as part of scrollback.
https://github.com/galatolofederico/st-sixel/compare/b3a1f5b...b50be82

I don't see that Federico Galatolo have made any changes to the sixel logic, so I would think that https://github.com/charlesdaniels/st would be the point of reference.

**Comment by schrmh** [comment]
Tbh the thing scrollback is a real bummer. 
But with st-sixel I always have two times the same sixel image next to each other and they always have some big black border. And when I hold the left mouse key and mark above the sixels then they vanish.
Also both mentioned forks are not maintained anymore and are forks of older st versions.

**Comment by bakkeby** [comment]
Can you guys try the above changes wrt scrollback of sixel images? The images flicker when they are moved but I suppose that is to be expected.

I'll remove the OSC 10 and 11 changes ref.
https://github.com/galatolofederico/st-sixel/compare/b3a1f5b...b50be82#diff-f51e7c2b25fcd7d1c288faf4b2445e48247c073d4cbf7ead8f3832f216683ba3R1987-R1995

As they just show up in my terminal as plain text:
```sh
$ 10;rgb:0000/0000/000011;rgb:ffff/ffff/ffff
```

If this is needed then one should probably use the OSC_10_11_12_2_PATCH instead.

**Comment by Barbarossa93** [comment]
It could be entirely possible that it is the result of a patch conflict, but unfortunately the images seem to flicker once and then disappear. I thought perhaps it was the sync patch, but it's not; so I'm unsure of what may cause it.

**Comment by avih** [comment]
> I'm unsure of what may cause it.

There's just one way to be sure: try out the original.

If sixel is a patch, then apply it to a fresh copy of st and see how it behaves. If it's a repository with a long sequence of (sixel related) commits on top of st-master, then simply build this repository and check it out.

If the original (patch or repository) works but it doesn't work in flexipatch, then feel free to try and figure out where the patch gets it wrong.

Either way, you should first test how it behaves with the original.

**Comment by bakkeby** [comment]
What do you guys use to view sixel graphics?

If I use sixel graphics with gnuplot and when I quit gnuplot the image is deleted leaving a blank space.

This seems to be intentional. If I remove the `im->should_delete = 1` in the `csihandle` function in st.c then the images do persist. I think that it should be fine deleting this. The images should be cleared anyway if you run the reset command.

**Comment by Barbarossa93** [comment]
I was just testing with a direct `img2sixel <image file>` but eventually and ideally I would incorporate `img2sixel` directly into my preview script for `lf`. Commenting out those lines work, but unfortunately using a simple `clear` isnt sufficient to remove images, a hard `reset` is needed. That may not pair well with a TUI program such as `lf`

**Comment by schrmh** [comment]
Similar experience as Barbarossa93 (additionally to the SIXEL patch I only have scrolling related patches enabled and images would disappear after scrolling). After removing the mentioned line I can scroll and images stay when I use lsix or my own pdfgrepSIXEL until I write reset.

**Comment by bakkeby** [comment]
Yes I think we can remove that purging of sixels code. Can always revisit if that introduces other issues down the line.

**Comment by schrmh** [comment]
Well, I think `clear` should actually clear the sixels but as a mid-term solution that's ok. Now since b39782f a patched st with st-flexipatch is officially the only terminal emulator that my script works with as intended, haha. 

**Ah but something else still doesn't work** (sorry, I haven't mentioned on this issue before): **The drawing example** (https://github.com/libsixel/libsixel/tree/master/examples/drawing).
It works on xterm (only in fullscreen tho) but not with st-flexipatch.
When I execute it with the patched st and try to hold the left mouse to draw I get:
```
erresc: unknown private set/reset mode 8452
erresc: unknown csi ESC[1;1'z
erresc: unknown csi ESC['|
```
A few times I also got:
```
erresc: unknown private set/reset mode 80 
erresc: invalid color j=258, p=? 
```
(but can't reproduce that anymore.)

The black drawing area actually appears; I set a different background colour with `printf %b '\e]11;#0000ff\a'` once to confirm that.

**Comment by schrmh** [comment]
I also found https://github.com/kovidgoyal/kitty/issues/3737#issuecomment-862843100
I tried the command in st-flexipatch and it does not work as described.
As mentioned at the first post in this issue, DECDMAC and DECINVM are mentioned in the libsixel documention. At least `img2sixel` can make use of that, so it might be worth to add that.

**Comment by schrmh** [comment]
Why was the 
```
for (im = term.images; im; im = im->next) {
			im->should_delete = 1;
}
```
right  under case 'J' anyways instead of in case 2? When I add it there SIXELs get removed as expected on `clear` but for some reason there is still some space and text doesn't get cleared, when it is outside of the screen. But this is also the case when I don't output SIXELs (tho I haven't tried it without the SIXEL patch turned off so far).
In fact, is E3 even supported? I mean when you look at the man page of `clear`, they say `one could clear the scrollback using printf '\033[3J'`.. so shouldn't there a case 3 within case 'J'?

**Comment by bakkeby** [comment]
Good questions.

> Why was the should_delete code right under case 'J' anyways?

That comes as-is from:
https://github.com/galatolofederico/st-sixel/compare/b3a1f5b...b50be82

As the comment says it would make sense to move it to the different sub cases, like only clearing visible images in case 2 (screen) and to clear all images and scrollback history in case 3.

It wasn't that obvious to work out how to clear the history but I think I got that to work.

I'll get back to you regarding the other points.

**Comment by schrmh** [comment]
> It wasn't that obvious to work out how to clear the history but I think I got that to work.
So it works on your machine? Huh. For me it doesn't seem to go into case 3. Tho the code you added (including the change in st.info) is there when I apply the scrollback and the SIXEL patch and the famous `SIXEL_C = sixel.c sixel_hls.c` to the Makefile.
Writing two times `clear` to clear the scrollback worked on other terminal emulators I used before (tho most I used clear everything including the scrollback when I write it once — so that could also be a configuration option I think).
So is there some other patches that I need? Something else I might be missing?

**Comment by bakkeby** [comment]
Scrollback appears to be cleared all other terminals I tried, in st it is just a bit odd how you are allowed to scroll up even though there is no history (wonder if it is worth addressing that).

It did work for me, the change to st.info is needed for it to call the clear function when that escape code comes through. Adding some print statements makes it easier to see which of the cases you enter (typically it will be 2 and 0 or 3 or 0) + run st from a terminal so that you can see the output of course.

I guess you could make it a configuration option for case 3, but I am not sure if it is possible to make the content of st.info configurable as such.

**Comment by schrmh** [comment]
So I added `fprintf(stderr, "Case x");` for each case.
So indeed, when I press enter or tab I get into Case 0.
When I write clear, no matter how many times, I get Case 0.
But the interesting thing is that when I literally take and send `printf '\033[3J'` from the man page of `clear` it goes into Case 3. It clears the screen but leaves a bunch of blocks that doesn't seem to be anything (when I copy it and enter it in some unicode dectection tool I get nothing. [fctix 5](https://wiki.archlinux.org/title/Fcitx5#How_to_view_the_Unicode_encoding_of_selected_characters) shows me a single U+000a there (tho at first it also showed me stuff I had in the clipboard so it might not be trustworthy for that here) ![image](https://user-images.githubusercontent.com/32062480/126196237-43a9727d-3689-4fe7-868d-bce5a433f208.png)

So I don't know why `clear` has a different output than the print statement from its very own manpage. I use Arch Linux thus I don't use any deprecated version of it. Switching the shell also makes no difference regarding the behaviour..

**Comment by bakkeby** [comment]
Did you try the above with the change to st.info?

```diff
-    clear=\E[H\E[2J,
+    clear=\E[H\E[3J,
```
Recompiling with that made it hit case 3 for me instead of case 2.

**Comment by schrmh** [comment]
Yes, st.info contains the 3J in line 13.
As I wrote, I freshly cloned the repo after your change. I even mentioned "(including the change in st.info)"

**Comment by bakkeby** [comment]
That's odd.

The only thing in the build that refers to st.info is this line in the Makefile:
```sh
tic -sx st.info
```

The man page for tic says that it will try to write to /usr/share/terminfo and if it can't do that then it will use ~/.terminfo (or ~/.terminfo.db).

This only executes when you install st, so I guess just running `make` won't make a difference.

**Comment by schrmh** [comment]
Ah, Indeed.. That's a bit unfortunate but fine for now.
I ran `sudo make install` and now I seem to get `^[[H^[[3J`.

**Comment by schrmh** [comment]
So to add another thing.. Maybe DRCS is not (fully) supported by st-flexipatch?

There is work done to get SIXEL into vim and that is using DRCS: https://github.com/nat-chan/Neovim-DRCS-SIXEL-dtach
https://youtu.be/o3NygmN5lHM?t=1561

In mlterm that feature works (open the AppImage, write `:terminal`, press enter and test with e.g. `img2sixel`.
With st-flexipatch those lines will be spit out to the TE I opened st with:
```
erresc: unknown private set/reset mode 80
erresc: invalid color j=258, p=?
erresc: unknown csi ESC[14t
erresc: unknown csi ESC[22;0t
erresc: invalid color j=258, p=?
erresc: unknown str ESC]5379
erresc: unknown private set/reset mode 8800
erresc: unknown csi ESC[1;0;0;7;1;3;14;0{
```
(there are more lines but stuff repeats — maybe it prints forever... All further lines start with the last erresc line and get longer..)

This can also be used to test for DRCS: https://github.com/saitoha/PyDRCS can be used (python2 virtual environment needed)

There are a few japanese blog entries about using DRCS with SIXEL and what pros it has:
https://qiita.com/arakiken/items/626b02cd857d20c12fbc
https://qiita.com/kefir_/items/78e64c545a70a0ebea8a

**Comment by siduck** [comment]
@bakkeby Hi! nice build, I couldnt find the sixel patch in the repo

![image](https://user-images.githubusercontent.com/59060246/180357440-5a8ab841-16d9-4e43-85eb-5e4c502d46cc.png)

**Comment by bakkeby** [comment]
No I don't have any standalone patches for sixel, just bespoke builds as referred to in the issue description.

**Comment by siduck** [comment]
> No I don't have any standalone patches for sixel, just bespoke builds as referred to in the issue description.

hmm then ig i need to patch manually from https://github.com/bakkeby/st-flexipatch/search?q=sixel&type= 

btw what patches besides alpha does sixel affect?

**Comment by bakkeby** [comment]
Besides alpha you have the scrollback patches obviously, but I don't remember it conflicting with anything else in particular.

**Comment by cronyakatsuki** [comment]
Hello, how can I use the sixel support provided in this repo in my personal st build?

**Comment by bakkeby** [comment]
@cronyakatsuki I suppose your best option is to set up st-flexipatch with the patches you have applied to your personal build, then finalise that build using the flexipatch-finalizer script, then replace the .git directory with the .git directory of a plain unpatched st build in order to get a diff. Wherever you just use git diff or you commit and create a patch file is up to you, but in any case I'd recommend manually patching the changes by hand as there will be changes that are unrelated to the sixel patch and thus unnecessary. Sixel support in st still has some problems I believe and it is not fully compatible with all other patches.
