### ISSUE TITLE
Patch Request: Ligatures

### ISSUE THREAD

**Issue by smhmd** [bakkeby/st-flexipatch#4]
Request: https://st.suckless.org/patches/ligatures/

Thanks.

**Comment by bakkeby** [comment]
Hi @smhmd,

took a while to get around to this. I was playing around with this when the patch first came out. I wanted to have it placed in the /patch directory like the other patches, but that turned out to be problematic considering how the new binary sources st.h.

I have added this now as-is and can confirm that it works. To enable it you need to set the LIGATURES_PATCH option to 1 in patches.h and also uncomment build lines in both Makefile and config.mk (and of course use a font that supports ligatures).

\
Thanks,

-Stein
