### ISSUE TITLE
"/usr/bin/ld: cannot find -lXcursor" when compiling

### ISSUE THREAD

**Issue by kenardes** [bakkeby/st-flexipatch#5]
when i run ```make``` command, then it'll show error:
```
/usr/bin/ld: cannot find -lXcursor
collect2: error: ld returned 1 exit status
make: *** [Makefile:33: st] Error 1
```

after install libxcursor-dev , there's no more error.

If i compile the original source code from suckless.org , everything is fine and i don't have to install this extra dependency (libxcursor-dev), so can you remove this extra dependency or tell us explicitly why we need to install this extra dependency?

```
## my system:
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        testing
Codename:       bullseye

$ uname -a
Linux debian 5.6.0-1-amd64 #1 SMP Debian 5.6.7-1 (2020-04-29) x86_64 GNU/Linux
```

**Comment by bakkeby** [comment]
Ah right, it will be because one or more of the patches need it. It is similar to how the `alpha` patch adds dependency on `-lXrender`.

I'll remove that and add a note to uncomment a line in the `config.mk` file when enabling the relevant patch, similarly to how I have it in dwm-flexipatch, e.g.
https://github.com/bakkeby/dwm-flexipatch/blob/master/config.mk#L23-L24
https://github.com/bakkeby/dwm-flexipatch/blob/master/patches.def.h#L22-L23

Thanks for reporting.
