### ISSUE TITLE
`ANYSIZE_NOBAR_PATCH` causes span on `xev` output

### ISSUE THREAD

**Issue by PRESFIL** [bakkeby/st-flexipatch#58]
I don't know yet if this is a bug or not. But since `ANYSIZE_NOBAR_PATCH` causes
a redraw, which causes `hxev` to spam a continuous stream of messages like:

```
PropertyNotify event, serial 34, synthetic NO, window 0x2600001,
    atom 0x157 (_NET_WM_STATE), time 2364461, state PropertyNewValue
```

This is reproducible as it turns out to be Xmonad but not in dwm, so it's not clear if this
is a bug or Xmonad's distinction.

**Comment by bakkeby** [comment]
This happens on dwm as well, it is just that dwm by default do not do much logging.

This happens due to this one line that sets class and size hints every single time the screen is refreshed:
https://github.com/bakkeby/st-flexipatch/blob/master/x.c#L3289

You can comment it out should you actually need that patch.

**Comment by bakkeby** [comment]
The `ANYSIZE_NOBAR_PATCH` was removed following pull request #75 which addressed border issues in the original patch. Artefacts should no longer appear with the `ANYSIZE_PATCH` and the redraw that the `ANYSIZE_NOBAR_PATCH` introduced is no longer necessary.

Going to mark this as closed.
