### ISSUE TITLE
How `ANYSIZE`s are related to each other

### ISSUE THREAD

**Issue by PRESFIL** [bakkeby/st-flexipatch#59]
Currently there are 3 similar patches:

- ANYSIZE_PATCH
- ANYSIZE_NOBAR_PATCH
- ANYSIZE_SIMPLE_PATCH

but under none of them is written about their relationships (they conflict with each other
or one depends on the other).

**Comment by bakkeby** [comment]
If you have no patch (i.e. default st behaviour) then st will:
   - set the size hints of st such that it can only be resized at certain increments (column width, line height)

The effect of this is that st will only resize one column and one row at a time which can seem a bit choppy although the (inner) borders will always remain the same.

The `ANYSIZE_PATCH` ( https://st.suckless.org/patches/anysize/ ) does two things:
   - it sets the size hints of st such that it can be resized to any size and
   - it centers the content of the terminal so that the border on the left hand side is as wide as the right hand side

The practical effect of this is that if you try to resize the st terminal slowly then the content will seem to swim (wobble) inside the st window. A side effect of this is that can result in black bars being drawn depending on the terminal background colour used.

The `ANYSIZE_NOBAR_PATCH` ( https://github.com/connor-brooks/st-anysize-nobar ) is an addon patch for the anysize patch and aims to prevent black bars by doing a redraw every cycle (by the looks of it anyway). It doesn't make much sense to use this on its own.

The `ANYSIZE_SIMPLE_PATCH` is a standalone patch that does one thing:
   - it sets the size hints of st such that it can be resized to any size

The effect of this is that the st window can be resized smoothly and the content remains in place (anchored to the top left corner) as normal. This also means that depending on the size of the terminal there may be more space at the bottom and on the right than the default border on the left and top.

Using this patch in combination with the `ANYSIZE_PATCH` would make no difference.
