### ISSUE TITLE
patching st-flexipath/config.h with st-solarized-dark-0.5.diff

### ISSUE THREAD

**Issue by plum** [bakkeby/st-flexipatch#6]
Hello, thanks for an excellent tool.  Having patched and installed included patches to my heart's content, I now wish to patch st-solarized-dark-0.5.diff, which isn't included. The perequisite no-bold-colors.diff is included  in flexiptach. Can I just patch st-flexipatch/config by hand  at the alpha patch stage? Or, must I await it's possible inclusion into the flexiptach project?

**Comment by bakkeby** [comment]
Hi there,

> Can I just patch st-flexipatch/config.h by hand

Of course, that's where you add your personal configuration. You can make any changes you want in config.h.

I intentionally skipped all patches that deal with colour themes as it's just configuration options and including all of them would just bloat the default configuration more than necessary.

That said, you may want to consider using the xresources patch and have your colour themes in your .Xresources file, e.g.

```
/* !! solarized dark */
*.color0:	#073642
*.color1:	#dc322f
*.color2:	#859900
*.color3:	#b58900
*.color4:	#268bd2
*.color5:	#d33682
*.color6:	#2aa198
*.color7:	#eee8d5
*.color9:	#cb4b16
*.color8:	#fdf6e3
*.color10:	#586e75
*.color11:	#657b83
*.color12:	#839496
*.color13:	#6c71c4
*.color14:	#93a1a1
*.color15:	#fdf6e3
```
(use the st. prefix rather than *. if you only want the theme to apply to st)

\
Thanks,

-Stein

**Comment by plum** [comment]
Thanks for your kind reply Steve. I beleive your suggestion concerning
use of Xresources is ideal. 
Kind Regards, John
