### ISSUE TITLE
pywal with st only applying color scheme after typing it in terminal

### ISSUE THREAD

**Issue by benilol98** [bakkeby/st-flexipatch#77]
i have the command "wal -i ~/Downloads/wallpaper.jpg" in my autostart but st starts with the default colors, after typing the same command in the terminal it works

**Comment by bakkeby** [comment]
This doesn't actually have anything to do with st or any other terminal emulator for that matter.

pywal will produce:
   - Xresources and
   - terminal escape sequences

(and other configuration, but that is not relevant in this case)

When you run the wal command it will (or should) send escape codes to each running terminal so that the colours change. This does not apply for new terminal windows, however.

If your st is patched to load Xresources on startup then it will load the colour resources that pywal produced.

If your st is not patched to load Xresources then the expectation is that you have your shell load the escape sequences on startup. These are stored in `~/.cache/wal/sequences` (or `$XDG_CACHE_HOME/wal/sequences` if you have that environment variable set).

The escape codes are loaded like this:

```sh
(cat ~/.cache/wal/sequences &)
```

When I used pywal in the past I used the following script to only load the escape sequences if I am in a non-login interactive shell (i.e. not ssh'ed in or trying to scp or anything like that):

```bash
$ cat ~/bin/inc/wal_restore.inc
#!/bin/bash
#
# Refer to:
#   https://github.com/dylanaraps/pywal

# Set wal color scheme on load if:
#    - a cached color scheme exists and
#    - we are in an interactive shell and
#    - we are not in a login shell
#
# This to avoid setting the color scheme when ssh-ing into the
# box as well as when using other tools like scp.

CACHE_DIR=${XDG_CACHE_HOME:-~/.cache}/wal

if [ -f $CACHE_DIR/sequences ]; then
    if [[ $- == *i* ]]; then
        if [ $ZSH_VERSION ]; then
            if [[ ! -o login ]]; then
                (cat $CACHE_DIR/sequences &)
                clear
            fi
        else
            shopt -q login_shell
            if [[ $? != 0 ]]; then
                (cat $CACHE_DIR/sequences &)
                clear
            fi
        fi
    fi
fi
```

I would then have this in my .bashrc or .zshrc:

```sh
source ~/bin/inc/wal_restore.inc
```

I'm sure the script could be simplified.

**Comment by bakkeby** [comment]
Maybe this is simpler.

```sh
#!/bin/bash
#
# Refer to:
#   https://github.com/dylanaraps/pywal

# Set wal color scheme on load if:
#    - a cached color scheme exists and
#    - we are in an interactive shell and
#    - we are not in a login shell
#
# This to avoid setting the color scheme when ssh-ing into the
# box as well as when using other tools like scp. 

if [ -f ${XDG_CACHE_HOME:-~/.cache}/wal/sequences ]; then
	if [[ $- == *i* ]]; then
		if [ $ZSH_VERSION ]; then
			[[ ! -o login ]] && LOAD_SEQUENCES=1
		else
			shopt -q login_shell || LOAD_SEQUENCES=1
		fi

		if [[ ! -z $LOAD_SEQUENCES ]]; then
			(/bin/cat ${XDG_CACHE_HOME:-~/.cache}/wal/sequences &)
			unset LOAD_SEQUENCES
			clear
		fi
	fi
fi

```

**Comment by benilol98** [comment]
Thank you for the answer, makes sense. Which patch would I need to load from Xresources?

**Comment by bakkeby** [comment]
That would be the [xresources](https://st.suckless.org/patches/xresources/) patch or the [xresources with signal reloading](https://st.suckless.org/patches/xresources-with-reload-signal/) patch.

In st-flexipatch that would be these toggles:
https://github.com/bakkeby/st-flexipatch/blob/9e0e41978125213d4469a30d05047a3484b13a7d/patches.def.h#L415-L425

**Comment by benilol98** [comment]
Alright tysm!

**Comment by benilol98** [comment]
Sorry for reopening but it doesn't work even with the patches applied

**Comment by bakkeby** [comment]
Can you clarify what exactly does not work?

You have many wheels in motion.

**Comment by benilol98** [comment]
The color scheme isn't being applied

**Comment by bakkeby** [comment]
Sure, but it is not clear what you did respective to your expectations.

Did you change `XRESOURCES_PATCH` in your `patches.h` file (not the default `patches.def.h`) file.

Did you recompile? Did you install? Did you run `wal` after starting up?

**Comment by benilol98** [comment]
Oh I'm so stupid I was modifying the patches.def.h, thanks.
